### ISSUE TITLE
permissions

### ISSUE THREAD

**Issue by BL5-Reinhardt** [HarryPotterSpells/harrypotterspells.github.com#1]
only ops can use spells how do i set for everyone else, the help on permissions is very vague

**Comment by jacklin213** [comment]
Apologies @BL5-Reinhardt not sure why I didn't get notified of this.
By default spell casting is set to ops. To allow everyone else to cast you will need to grant the permission
```- harrypotterspells.cast```

As shown in the permissions section: https://harrypotterspells.github.io/commands.html#other-permissions
Hope this helps
